# -*- coding: utf-8 -*-
"""HAQIQIY Postgres CHECK yozuvlari — `pg_get_expr(conbin, conrelid)` (oddiy va `pretty`).

Qo'lda yozilmagan: faqat o'qiydigan katalog so'rovi bilan olingan (Phase 4A.1, 2026-09-14):
  · PG 16.2  — mahalliy pgserver, `initdb` dan keyin;
  · PG 18.6  — staging (`default_transaction_read_only=on`), commit 68f73ae.
Ikki versiya 25 cheklovning HAMMASINI aynan bir xil yozdi. Bu fayl test EMAS
(`test_` bilan boshlanmaydi) — `tests/test_check_canon.py` uni ishlatadi.

Kalit: (sxema, jadval, cheklov, oddiy_ifoda, pretty_ifoda).
"""
RENDERINGS = [
    ('cash', 'cash_ledger_entries', 'cle_amount_pos',
     '(amount > (0)::numeric)',
     'amount > 0::numeric'),
    ('cash', 'cash_ledger_entries', 'cle_leg_nonneg',
     '(leg_index >= 0)',
     'leg_index >= 0'),
    ('cash', 'cash_ledger_entries', 'cle_no_self_rev',
     '((reverses_id IS NULL) OR (reverses_id <> id))',
     'reverses_id IS NULL OR reverses_id <> id'),
    ('cash', 'cash_ledger_entries', 'cle_posting_shift',
     "(((posting_kind = ANY (ARRAY['ON_SHIFT'::cash.cash_posting_kind, 'LATE_SYNC'::cash.cash_posting_kind])) AND (shift_id IS NOT NULL)) OR ((posting_kind = 'OFF_SHIFT'::cash.cash_posting_kind) AND (shift_id IS NULL)))",
     "(posting_kind = ANY (ARRAY['ON_SHIFT'::cash.cash_posting_kind, 'LATE_SYNC'::cash.cash_posting_kind])) AND shift_id IS NOT NULL OR posting_kind = 'OFF_SHIFT'::cash.cash_posting_kind AND shift_id IS NULL"),
    ('cash', 'cash_ledger_entries', 'cle_recon_prov',
     "(((provenance = 'RECONSTRUCTION'::cash.cash_provenance) AND (reconstruction_reason IS NOT NULL) AND (reconstruction_source_ref IS NOT NULL)) OR ((provenance = 'NORMAL'::cash.cash_provenance) AND (reconstruction_reason IS NULL) AND (reconstruction_source_ref IS NULL)))",
     "provenance = 'RECONSTRUCTION'::cash.cash_provenance AND reconstruction_reason IS NOT NULL AND reconstruction_source_ref IS NOT NULL OR provenance = 'NORMAL'::cash.cash_provenance AND reconstruction_reason IS NULL AND reconstruction_source_ref IS NULL"),
    ('cash', 'cash_ledger_entries', 'cle_transfer_group_iff',
     "((category = 'TRANSFER'::cash.cash_category) = (transfer_group_id IS NOT NULL))",
     "(category = 'TRANSFER'::cash.cash_category) = (transfer_group_id IS NOT NULL)"),
    ('cash', 'cash_ledger_exceptions', 'cx_resolved_iff',
     "((state = 'RESOLVED'::cash.cash_exception_state) = (resolved_at IS NOT NULL))",
     "(state = 'RESOLVED'::cash.cash_exception_state) = (resolved_at IS NOT NULL)"),
    ('cash', 'cash_transfers', 'ct_amount_pos',
     '(amount > (0)::numeric)',
     'amount > 0::numeric'),
    ('cash', 'cash_transfers', 'ct_no_self',
     '(from_account_id <> to_account_id)',
     'from_account_id <> to_account_id'),
    ('cash', 'negative_cash_approvals', 'nca_amount_pos',
     '(amount > (0)::numeric)',
     'amount > 0::numeric'),
    ('cash', 'negative_cash_approvals', 'nca_scope',
     "((direction = 'OUT'::cash.cash_direction) AND (account_type = 'TILL'::cash.cash_account_type))",
     "direction = 'OUT'::cash.cash_direction AND account_type = 'TILL'::cash.cash_account_type"),
    ('cash', 'reconciliation_records', 'rr_account_target_safe',
     "(((target_type = 'ACCOUNT'::cash.cash_recon_target) AND (account_type = 'SAFE'::cash.cash_account_type)) OR ((target_type = 'SHIFT'::cash.cash_recon_target) AND (account_type IS NULL)))",
     "target_type = 'ACCOUNT'::cash.cash_recon_target AND account_type = 'SAFE'::cash.cash_account_type OR target_type = 'SHIFT'::cash.cash_recon_target AND account_type IS NULL"),
    ('cash', 'reconciliation_records', 'rr_seq_pos',
     '(seq >= 1)',
     'seq >= 1'),
    ('cash', 'reconciliation_records', 'rr_target_exactly_one',
     "(((target_type = 'SHIFT'::cash.cash_recon_target) AND (shift_id IS NOT NULL) AND (cash_account_id IS NULL)) OR ((target_type = 'ACCOUNT'::cash.cash_recon_target) AND (cash_account_id IS NOT NULL) AND (shift_id IS NULL)))",
     "target_type = 'SHIFT'::cash.cash_recon_target AND shift_id IS NOT NULL AND cash_account_id IS NULL OR target_type = 'ACCOUNT'::cash.cash_recon_target AND cash_account_id IS NOT NULL AND shift_id IS NULL"),
    ('cash', 'shifts', 'sh_closed_iff',
     "((status = 'CLOSED'::cash.cash_shift_status) = (closed_at IS NOT NULL))",
     "(status = 'CLOSED'::cash.cash_shift_status) = (closed_at IS NOT NULL)"),
    ('cash', 'shifts', 'sh_type_till',
     "(account_type = 'TILL'::cash.cash_account_type)",
     "account_type = 'TILL'::cash.cash_account_type"),
    ('cash', 'shifts', 'sh_window',
     '((closed_at IS NULL) OR (closed_at > opened_at))',
     'closed_at IS NULL OR closed_at > opened_at'),
    ('public', 'lot_shortfall_resolutions', 'ck_lsr_kind',
     "((kind)::text = ANY ((ARRAY['real'::character varying, 'netting'::character varying])::text[]))",
     "kind::text = ANY (ARRAY['real'::character varying, 'netting'::character varying]::text[])"),
    ('public', 'lot_shortfall_resolutions', 'ck_lsr_netting_zero',
     "(((kind)::text <> 'netting'::text) OR (variance = (0)::numeric))",
     "kind::text <> 'netting'::text OR variance = 0::numeric"),
    ('public', 'lot_shortfall_resolutions', 'ck_lsr_qty_pos',
     '(qty > (0)::numeric)',
     'qty > 0::numeric'),
    ('public', 'lot_shortfall_resolutions', 'ck_lsr_variance_identity',
     '(variance = (actual_cost - provisional_cost))',
     'variance = (actual_cost - provisional_cost)'),
    ('public', 'lot_shortfalls', 'ck_lot_shortfall_resolved_le_qty',
     '(resolved_qty <= qty)',
     'resolved_qty <= qty'),
    ('public', 'products', 'ck_track_expiry_implies_lots',
     '((NOT track_expiry) OR track_lots)',
     'NOT track_expiry OR track_lots'),
    ('public', 'return_item_resolution_allocations', 'ck_rira_qty_pos',
     '(qty > (0)::numeric)',
     'qty > 0::numeric'),
    ('public', 'return_item_shortfall_allocations', 'ck_risa_qty_pos',
     '(qty > (0)::numeric)',
     'qty > 0::numeric'),
]
